project:
  type: website
  output-dir: docs

website:
  title: "Tanishq Katheriya"
  favicon: images/favicon.ico
  navbar:
    logo: images/logo.png
    logo-alt: "TK"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Reflections"
        href: reflections.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "CV"
        href: docs/resume.pdf
        target: _blank
      - icon: github
        href: https://github.com/Tanishq-katheriya
        target: _blank
  

format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: false

execute:
  freeze: auto
